"""Added title field

Revision ID: 302066e9abd4
Revises: bd85231da26a
Create Date: 2023-12-10 01:52:16.964444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302066e9abd4'
down_revision = 'bd85231da26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=100000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.String(length=100000),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###
